# Jekyll configuration

name: Zen
description: Welcome to Zen's blogÔºÅ

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/xinzen/xinzen.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/jekyll-xixia'
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "zh" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
